[project]
name = "kaspbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adaptix>=3.0.0b11",
    "aioboto3>=15.5.0",
    "aiogram>=3.22.0",
    "asyncpg>=0.30.0",
    "sqlalchemy>=2.0.44",
    "uuid6>=2025.0.1",
]
